import { signToken, verifyToken } from '../../utils/jwt';

describe('JWT utils', () => {
  const payload = { userId: 'user-123', email: 'test@test.com' };

  it('signToken returns a non-empty string', () => {
    const token = signToken(payload);
    expect(typeof token).toBe('string');
    expect(token.length).toBeGreaterThan(0);
  });

  it('verifyToken decodes a token generated by signToken', () => {
    const token = signToken(payload);
    const decoded = verifyToken(token);
    expect(decoded.userId).toBe(payload.userId);
    expect(decoded.email).toBe(payload.email);
  });

  it('verifyToken throws on an invalid token', () => {
    expect(() => verifyToken('invalid.token.here')).toThrow();
  });

  it('verifyToken throws on an empty string', () => {
    expect(() => verifyToken('')).toThrow();
  });
});
